name: Release to Github Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: target/site

jobs:
  Github-Pages-Release:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly

      - uses: cargo-bins/cargo-binstall@main

      - run:  cargo binstall cargo-leptos -y

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - run: cargo install cargo-leptos

      - run: cargo leptos build --release

      - run: PRERENDER_ONLY=true ./target/release/speakingof

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/site

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4